repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: check-added-large-files
    - id: check-json
    - id: check-toml
    - id: check-xml
    - id: check-yaml
    - id: debug-statements
    - id: detect-aws-credentials
      args: [--allow-missing-credentials]
    - id: detect-private-key
    - id: end-of-file-fixer
    - id: name-tests-test
      args: [--django]  # to match `test*.py`.
    - id: no-commit-to-branch   # to protect specific branches from direct checkins.
      args: [--branch, master]
    - id: pretty-format-json
      args: [--autofix]

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
    - id: flake8
      args: [--config=.flake8]
      additional_dependencies: [flake8-bugbear, flake8-eradicate, pep8-naming, flake8-expression-complexity, flake8-cognitive-complexity]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.0
    hooks:
      - id: mypy
        args: [--ignore-missing-imports]
        additional_dependencies: [tokenize-rt==3.2.0]

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
    - id: black
      language_version: python3

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black"]

  # for docstrings in python codes
  - repo: https://github.com/myint/docformatter
    rev: v1.7.5
    hooks:
      - id: docformatter
        args: [--in-place]
